name: portfolio

services:
  portfolio.api:
    image: ${DOCKER_REGISTRY-}portfolioapi
    container_name: portfolio-api
    build:
      context: ..
      dockerfile: src/Portfolio.API/Dockerfile
    ports: 
      - "12345:8081"

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: Test123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  